"""initial_schema — baseline for all NexusGuard tables, ENUMs, and indexes.

This is a BASELINE migration — it represents the schema that was previously
managed by db/schema.sql. It was written by hand, not autogenerated.

If your DB was already created from db/schema.sql (e.g. via docker-compose),
DO NOT run this migration — instead stamp it as applied:

    alembic stamp 0001

If you are setting up a fresh database:

    alembic upgrade head

The downgrade() fully tears down all NexusGuard objects in safe FK order.

Revision ID: 0001
Revises:
Create Date: 2026-04-13 00:00:00.000000

Dependency order for upgrade():
  1. Extensions (uuid-ossp, pgcrypto)
  2. ENUM types            — must precede every table that uses them
  3. organizations         — no FK dependencies
  4. users                 — FK → organizations
  5. roles                 — no FK dependencies
  6. permissions           — no FK dependencies
  7. role_permissions      — FK → roles, permissions
  8. user_roles            — FK → users, roles
  9. sod_rules             — FK → permissions
  10. sod_violations       — FK → users, sod_rules, permissions
  11. access_logs          — FK → users  (partitioned)
  12. risk_scores          — FK → users
  13. risk_baselines       — FK → users
  14. review_campaigns     — no FK dependencies (created_by is untyped UUID)
  15. review_items         — FK → review_campaigns, users, roles, permissions
  16. audit_events         — no FK dependencies (actor/target are untyped UUIDs)
  17. deprovision_queue    — FK → users
  18. Indexes
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ---------------------------------------------------------------------------
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
# ---------------------------------------------------------------------------


def upgrade() -> None:
    # ── 1. PostgreSQL extensions ──────────────────────────────────────────
    # uuid_generate_v4() requires uuid-ossp.
    # pgcrypto provides gen_random_bytes() used in future hash operations.
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ── 2. ENUM types ─────────────────────────────────────────────────────
    # CRITICAL: Every ENUM must be created BEFORE the first table that uses it.
    # Using IF NOT EXISTS guards means this migration is safe to retry.
    #
    # Why op.execute() instead of sa.Enum(...).create()?
    #   sa.Enum(...).create(op.get_bind()) is synchronous-only and breaks in
    #   async Alembic setups. Raw SQL with IF NOT EXISTS is safer and explicit.

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE identity_class AS ENUM (
                'vendor', 'partner', 'contractor', 'customer', 'b2b_admin', 'auditor'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE identity_status AS ENUM (
                'pending', 'active', 'suspended', 'deprovisioned', 'expired'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE risk_tier AS ENUM (
                'critical', 'high', 'medium', 'low', 'minimal'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE sod_severity AS ENUM (
                'critical', 'high', 'medium', 'low'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE sod_status AS ENUM (
                'open', 'mitigated', 'accepted', 'false_positive', 'remediated'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE event_type AS ENUM (
                'login_success', 'login_failure', 'mfa_success', 'mfa_failure',
                'access_granted', 'access_denied', 'session_created', 'session_terminated',
                'data_export', 'admin_action', 'api_call', 'privilege_escalation',
                'off_hours_access', 'geo_anomaly', 'new_device', 'bulk_operation'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE campaign_status AS ENUM (
                'draft', 'active', 'paused', 'completed', 'cancelled'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE review_decision AS ENUM (
                'certified', 'revoked', 'escalated', 'pending'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE audit_category AS ENUM (
                'identity_lifecycle', 'access_change', 'authentication', 'authorization',
                'risk_event', 'review_action', 'sod_event', 'admin_action', 'system_event'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE deprovision_reason AS ENUM (
                'contract_expired', 'uar_revocation', 'risk_triggered', 'manual',
                'sod_violation', 'inactivity', 'organization_offboarding'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    # ── 3. organizations ──────────────────────────────────────────────────
    # Must come before users because users.organization_id FKs here.
    op.create_table(
        "organizations",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("name",       sa.String(255),  nullable=False),
        sa.Column("type",       sa.String(100),  nullable=True),   # vendor/partner/customer
        sa.Column("domain",     sa.String(255),  nullable=True),
        sa.Column("country",    sa.String(10),   nullable=True),
        sa.Column("risk_tier",
                  sa.Enum("critical", "high", "medium", "low", "minimal",
                          name="risk_tier", create_type=False),
                  server_default="medium"),
        sa.Column("baa_executed", sa.Boolean, server_default=sa.false()),
        sa.Column("pci_scoped",   sa.Boolean, server_default=sa.false()),
        sa.Column("gdpr_dpa",     sa.Boolean, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("metadata",   postgresql.JSONB, server_default=sa.text("'{}'")),
    )

    # ── 4. users ──────────────────────────────────────────────────────────
    # NOTE: organization (String) and organization_id (FK) both exist here.
    # Phase 1 Day 2 will migrate to organization_id as sole source of truth.
    # For this baseline migration we faithfully recreate schema.sql as-is.
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("external_id",  sa.String(255), unique=True,  nullable=True),
        sa.Column("email",        sa.String(255), unique=True,  nullable=False),
        sa.Column("first_name",   sa.String(100), nullable=False),
        sa.Column("last_name",    sa.String(100), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=True),
        sa.Column("identity_class",
                  sa.Enum("vendor", "partner", "contractor", "customer",
                          "b2b_admin", "auditor",
                          name="identity_class", create_type=False),
                  nullable=False),
        # Dual column — String kept for display, FK is source of truth
        sa.Column("organization",    sa.String(255), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status",
                  sa.Enum("pending", "active", "suspended", "deprovisioned", "expired",
                          name="identity_status", create_type=False),
                  server_default="pending", nullable=False),
        sa.Column("risk_tier",
                  sa.Enum("critical", "high", "medium", "low", "minimal",
                          name="risk_tier", create_type=False),
                  server_default="medium"),
        sa.Column("current_risk_score", sa.Numeric(5, 2), server_default="50.0"),
        sa.Column("source_system",    sa.String(100), nullable=True),
        sa.Column("contract_id",      sa.String(255), nullable=True),
        sa.Column("contract_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("onboarded_at",     sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login",       sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_risk_calc",   sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("metadata",   postgresql.JSONB, server_default=sa.text("'{}'")),
        # FK added after both tables exist
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"],
            name="fk_users_org",
        ),
    )

    # ── 5. roles ──────────────────────────────────────────────────────────
    op.create_table(
        "roles",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("name",         sa.String(255), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=True),
        sa.Column("description",  sa.Text,        nullable=True),
        sa.Column("scope",        sa.String(100), server_default="global"),
        sa.Column("system_name",  sa.String(100), nullable=True),
        sa.Column("risk_level",
                  sa.Enum("critical", "high", "medium", "low", "minimal",
                          name="risk_tier", create_type=False),
                  server_default="low"),
        sa.Column("is_sensitive",  sa.Boolean, server_default=sa.false()),
        sa.Column("is_privileged", sa.Boolean, server_default=sa.false()),
        sa.Column("owner_id",  postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("metadata", postgresql.JSONB, server_default=sa.text("'{}'")),
    )

    # ── 6. permissions ────────────────────────────────────────────────────
    op.create_table(
        "permissions",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("name",         sa.String(255), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=True),
        sa.Column("description",  sa.Text,        nullable=True),
        sa.Column("resource",     sa.String(255), nullable=False),
        sa.Column("action",       sa.String(100), nullable=False),
        sa.Column("system_name",  sa.String(100), nullable=True),
        sa.Column("is_sensitive", sa.Boolean, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )

    # ── 7. role_permissions ───────────────────────────────────────────────
    op.create_table(
        "role_permissions",
        sa.Column("role_id",       postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("permission_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("granted_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
        sa.ForeignKeyConstraint(["role_id"],       ["roles.id"],       ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
    )

    # ── 8. user_roles ─────────────────────────────────────────────────────
    op.create_table(
        "user_roles",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("expires_at",             sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by",            postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("business_justification", sa.Text,       nullable=True),
        sa.Column("status",                 sa.String(50), server_default="active"),
        sa.Column("revoked_at",             sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by",             postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("revocation_reason",      sa.Text, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
    )
    # Partial unique index: a user can only have ONE active assignment per role.
    # This is the DB-level guard against race conditions (Phase 5).
    op.create_index(
        "idx_user_roles_active",
        "user_roles",
        ["user_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )

    # ── 9. sod_rules ──────────────────────────────────────────────────────
    op.create_table(
        "sod_rules",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("name",        sa.String(255), nullable=False),
        sa.Column("description", sa.Text,        nullable=True),
        sa.Column("permission_a_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("permission_b_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("severity",
                  sa.Enum("critical", "high", "medium", "low",
                          name="sod_severity", create_type=False),
                  nullable=False, server_default="high"),
        sa.Column("compliance_control", sa.String(100), nullable=True),
        sa.Column("is_active", sa.Boolean, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["permission_a_id"], ["permissions.id"]),
        sa.ForeignKeyConstraint(["permission_b_id"], ["permissions.id"]),
    )

    # ── 10. sod_violations ────────────────────────────────────────────────
    op.create_table(
        "sod_violations",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("user_id",      postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sod_rule_id",  postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("permission_a_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("permission_b_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("status",
                  sa.Enum("open", "mitigated", "accepted", "false_positive", "remediated",
                          name="sod_status", create_type=False),
                  nullable=False, server_default="open"),
        sa.Column("severity",
                  sa.Enum("critical", "high", "medium", "low",
                          name="sod_severity", create_type=False),
                  nullable=False),
        sa.Column("remediation_action", sa.Text, nullable=True),
        sa.Column("remediated_at",      sa.DateTime(timezone=True), nullable=True),
        sa.Column("remediated_by",      postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("mitigating_control", sa.Text, nullable=True),
        sa.Column("accepted_by",        postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("accepted_at",        sa.DateTime(timezone=True), nullable=True),
        sa.Column("acceptance_reason",  sa.Text, nullable=True),
        sa.Column("review_due_date",    sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"],         ["users.id"]),
        sa.ForeignKeyConstraint(["sod_rule_id"],     ["sod_rules.id"]),
        sa.ForeignKeyConstraint(["permission_a_id"], ["permissions.id"]),
        sa.ForeignKeyConstraint(["permission_b_id"], ["permissions.id"]),
    )

    # ── 11. access_logs (partitioned by created_at) ───────────────────────
    # Alembic cannot manage partitioned tables natively, so we use raw SQL.
    # This is intentional: partition management is operational, not model-driven.
    op.execute("""
        CREATE TABLE IF NOT EXISTS access_logs (
            id          UUID DEFAULT uuid_generate_v4(),
            user_id     UUID NOT NULL REFERENCES users(id),
            event_type  event_type NOT NULL,
            resource    VARCHAR(255),
            action      VARCHAR(100),
            ip_address  INET,
            country     VARCHAR(10),
            city        VARCHAR(100),
            user_agent  TEXT,
            device_id   VARCHAR(255),
            session_id  VARCHAR(255),
            risk_score  DECIMAL(5,2),
            risk_factors JSONB DEFAULT '[]',
            success     BOOLEAN DEFAULT TRUE,
            metadata    JSONB DEFAULT '{}',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
        ) PARTITION BY RANGE (created_at)
    """)
    # Default catch-all partition (always created first)
    op.execute("""
        CREATE TABLE IF NOT EXISTS access_logs_default
            PARTITION OF access_logs DEFAULT
    """)
    # Quarterly partitions — add more each quarter via new migrations
    op.execute("""
        CREATE TABLE IF NOT EXISTS access_logs_2025_q2
            PARTITION OF access_logs
            FOR VALUES FROM ('2025-04-01') TO ('2025-07-01')
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS access_logs_2025_q3
            PARTITION OF access_logs
            FOR VALUES FROM ('2025-07-01') TO ('2025-10-01')
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS access_logs_2025_q4
            PARTITION OF access_logs
            FOR VALUES FROM ('2025-10-01') TO ('2026-01-01')
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS access_logs_2026_q1
            PARTITION OF access_logs
            FOR VALUES FROM ('2026-01-01') TO ('2026-04-01')
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS access_logs_2026_q2
            PARTITION OF access_logs
            FOR VALUES FROM ('2026-04-01') TO ('2026-07-01')
    """)

    # ── 12. risk_scores ───────────────────────────────────────────────────
    op.create_table(
        "risk_scores",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("user_id",         postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("score",           sa.Numeric(5, 2), nullable=False),
        sa.Column("previous_score",  sa.Numeric(5, 2), nullable=True),
        sa.Column("score_delta",     sa.Numeric(5, 2), nullable=True),
        sa.Column("risk_tier",
                  sa.Enum("critical", "high", "medium", "low", "minimal",
                          name="risk_tier", create_type=False),
                  nullable=False),
        sa.Column("contributing_factors", postgresql.JSONB,
                  server_default=sa.text("'{}'")),
        sa.Column("calculated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by",
                  sa.Enum("login_success", "login_failure", "mfa_success", "mfa_failure",
                          "access_granted", "access_denied", "session_created",
                          "session_terminated", "data_export", "admin_action", "api_call",
                          "privilege_escalation", "off_hours_access", "geo_anomaly",
                          "new_device", "bulk_operation",
                          name="event_type", create_type=False),
                  nullable=True),
        sa.Column("triggering_log_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    )

    # ── 13. risk_baselines ────────────────────────────────────────────────
    op.create_table(
        "risk_baselines",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("user_id",              postgresql.UUID(as_uuid=True),
                  nullable=False, unique=True),
        sa.Column("avg_login_hour",       sa.Numeric(4, 2),  nullable=True),
        sa.Column("typical_countries",    sa.ARRAY(sa.Text), nullable=True),
        sa.Column("typical_devices",      sa.ARRAY(sa.Text), nullable=True),
        sa.Column("avg_daily_api_calls",  sa.Integer, nullable=True),
        sa.Column("avg_session_duration", sa.Interval, nullable=True),
        sa.Column("last_calculated", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("sample_days", sa.Integer, server_default="30"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    )

    # ── 14. review_campaigns ──────────────────────────────────────────────
    op.create_table(
        "review_campaigns",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("name",         sa.String(255), nullable=False),
        sa.Column("description",  sa.Text,        nullable=True),
        sa.Column("status",
                  sa.Enum("draft", "active", "paused", "completed", "cancelled",
                          name="campaign_status", create_type=False),
                  nullable=False, server_default="draft"),
        sa.Column("campaign_type", sa.String(100), server_default="quarterly"),
        sa.Column("scope",         postgresql.JSONB, server_default=sa.text("'{}'")),
        sa.Column("created_by",    postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("start_date",    sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date",      sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at",  sa.DateTime(timezone=True), nullable=True),
        sa.Column("completion_rate", sa.Numeric(5, 2), nullable=True),
        sa.Column("total_items",     sa.Integer, server_default="0"),
        sa.Column("certified_count", sa.Integer, server_default="0"),
        sa.Column("revoked_count",   sa.Integer, server_default="0"),
        sa.Column("escalated_count", sa.Integer, server_default="0"),
        sa.Column("compliance_standard", sa.String(100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )

    # ── 15. review_items ─────────────────────────────────────────────────
    op.create_table(
        "review_items",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("campaign_id",  postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id",      postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role_id",      postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("permission_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewer_id",  postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("decision",
                  sa.Enum("certified", "revoked", "escalated", "pending",
                          name="review_decision", create_type=False),
                  server_default="pending"),
        sa.Column("decision_at",        sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_by",        postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("justification",      sa.Text, nullable=True),
        sa.Column("risk_score_at_review", sa.Numeric(5, 2), nullable=True),
        sa.Column("escalated_to",       postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("escalated_at",       sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_reason",  sa.Text, nullable=True),
        sa.Column("reminder_count",     sa.Integer, server_default="0"),
        sa.Column("last_reminder_at",   sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"],  ["review_campaigns.id"]),
        sa.ForeignKeyConstraint(["user_id"],      ["users.id"]),
        sa.ForeignKeyConstraint(["role_id"],      ["roles.id"]),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"]),
    )

    # ── 16. audit_events ─────────────────────────────────────────────────
    # sequence_num uses BIGSERIAL for monotonic ordering and hash-chain linking.
    # actor_id / target_user_id are untyped UUIDs (no FK) so the audit log
    # retains events even after a user is deleted — critical for GDPR tombstone.
    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("sequence_num",  sa.BigInteger, unique=True, nullable=False),
        sa.Column("category",
                  sa.Enum("identity_lifecycle", "access_change", "authentication",
                          "authorization", "risk_event", "review_action", "sod_event",
                          "admin_action", "system_event",
                          name="audit_category", create_type=False),
                  nullable=False),
        sa.Column("event_type",     sa.String(100), nullable=False),
        sa.Column("actor_id",       postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_email",    sa.String(255), nullable=True),
        sa.Column("target_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("target_email",   sa.String(255), nullable=True),
        sa.Column("resource_type",  sa.String(100), nullable=True),
        sa.Column("resource_id",    sa.String(255), nullable=True),
        sa.Column("action",         sa.String(100), nullable=False),
        sa.Column("outcome",        sa.String(50),  nullable=False),
        sa.Column("ip_address",     postgresql.INET, nullable=True),
        sa.Column("payload",        postgresql.JSONB, server_default=sa.text("'{}'")),
        sa.Column("previous_state", postgresql.JSONB, server_default=sa.text("'{}'")),
        sa.Column("new_state",      postgresql.JSONB, server_default=sa.text("'{}'")),
        sa.Column("event_hash",     sa.String(64), nullable=False),
        sa.Column("prev_hash",      sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )
    # sequence_num auto-increment via a PostgreSQL sequence
    op.execute("CREATE SEQUENCE IF NOT EXISTS audit_events_sequence_num_seq")
    op.execute("""
        ALTER TABLE audit_events
            ALTER COLUMN sequence_num
            SET DEFAULT nextval('audit_events_sequence_num_seq')
    """)

    # ── 17. deprovision_queue ────────────────────────────────────────────
    op.create_table(
        "deprovision_queue",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("uuid_generate_v4()"), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reason",
                  sa.Enum("contract_expired", "uar_revocation", "risk_triggered",
                          "manual", "sod_violation", "inactivity",
                          "organization_offboarding",
                          name="deprovision_reason", create_type=False),
                  nullable=False),
        sa.Column("triggered_by",  sa.String(255), nullable=True),
        sa.Column("scheduled_at",  sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("execute_at",    sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at",   sa.DateTime(timezone=True), nullable=True),
        sa.Column("status",        sa.String(50), server_default="queued"),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("systems_to_deprovision", sa.ARRAY(sa.Text), nullable=True),
        sa.Column("completion_evidence", postgresql.JSONB,
                  server_default=sa.text("'{}'")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    )

    # ── 18. Indexes ───────────────────────────────────────────────────────
    # users
    op.create_index("idx_users_email",            "users", ["email"])
    op.create_index("idx_users_status",           "users", ["status"])
    op.create_index("idx_users_identity_class",   "users", ["identity_class"])
    op.create_index("idx_users_risk_tier",        "users", ["risk_tier"])
    op.create_index("idx_users_org",              "users", ["organization_id"])
    op.create_index("idx_users_contract_expires", "users", ["contract_expires_at"])

    # access_logs (indexes go on the parent partitioned table)
    op.create_index("idx_access_logs_user",       "access_logs", ["user_id"])
    op.create_index("idx_access_logs_created",    "access_logs", ["created_at"])
    op.create_index("idx_access_logs_event_type", "access_logs", ["event_type"])

    # sod_violations
    op.create_index("idx_sod_violations_user",    "sod_violations", ["user_id"])
    op.create_index("idx_sod_violations_status",  "sod_violations", ["status"])

    # review_items
    op.create_index("idx_review_items_campaign",  "review_items", ["campaign_id"])
    op.create_index("idx_review_items_reviewer",  "review_items", ["reviewer_id"])
    op.create_index("idx_review_items_decision",  "review_items", ["decision"])

    # risk_scores
    op.create_index("idx_risk_scores_user",       "risk_scores", ["user_id"])
    op.create_index("idx_risk_scores_calculated", "risk_scores", ["calculated_at"])

    # audit_events
    op.create_index("idx_audit_events_sequence",  "audit_events", ["sequence_num"])
    op.create_index("idx_audit_events_actor",     "audit_events", ["actor_id"])
    op.create_index("idx_audit_events_target",    "audit_events", ["target_user_id"])
    op.create_index("idx_audit_events_created",   "audit_events", ["created_at"])
    op.create_index("idx_audit_events_category",  "audit_events", ["category"])


def downgrade() -> None:
    """
    Tear down the entire NexusGuard schema.
    Tables dropped in reverse FK dependency order.
    ENUM types dropped last (CASCADE handles any remaining references).
    """
    # ── Indexes (dropped automatically with tables, but explicit is cleaner) ──
    op.drop_index("idx_audit_events_category",  table_name="audit_events")
    op.drop_index("idx_audit_events_created",   table_name="audit_events")
    op.drop_index("idx_audit_events_target",    table_name="audit_events")
    op.drop_index("idx_audit_events_actor",     table_name="audit_events")
    op.drop_index("idx_audit_events_sequence",  table_name="audit_events")
    op.drop_index("idx_risk_scores_calculated", table_name="risk_scores")
    op.drop_index("idx_risk_scores_user",       table_name="risk_scores")
    op.drop_index("idx_review_items_decision",  table_name="review_items")
    op.drop_index("idx_review_items_reviewer",  table_name="review_items")
    op.drop_index("idx_review_items_campaign",  table_name="review_items")
    op.drop_index("idx_sod_violations_status",  table_name="sod_violations")
    op.drop_index("idx_sod_violations_user",    table_name="sod_violations")
    op.drop_index("idx_users_contract_expires", table_name="users")
    op.drop_index("idx_users_org",              table_name="users")
    op.drop_index("idx_users_risk_tier",        table_name="users")
    op.drop_index("idx_users_identity_class",   table_name="users")
    op.drop_index("idx_users_status",           table_name="users")
    op.drop_index("idx_users_email",            table_name="users")
    op.drop_index("idx_user_roles_active",      table_name="user_roles")

    # ── Tables in reverse FK order ─────────────────────────────────────────
    op.drop_table("deprovision_queue")
    op.drop_table("audit_events")
    op.execute("DROP SEQUENCE IF EXISTS audit_events_sequence_num_seq")
    op.drop_table("review_items")
    op.drop_table("review_campaigns")
    op.drop_table("risk_baselines")
    op.drop_table("risk_scores")
    # Drop partitioned table and all partitions (CASCADE handles children)
    op.execute("DROP TABLE IF EXISTS access_logs CASCADE")
    op.drop_table("sod_violations")
    op.drop_table("sod_rules")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("permissions")
    op.drop_table("roles")
    op.drop_table("users")
    op.drop_table("organizations")

    # ── ENUM types (CASCADE cleans up any straggling column references) ────
    op.execute("DROP TYPE IF EXISTS deprovision_reason CASCADE")
    op.execute("DROP TYPE IF EXISTS audit_category     CASCADE")
    op.execute("DROP TYPE IF EXISTS review_decision    CASCADE")
    op.execute("DROP TYPE IF EXISTS campaign_status    CASCADE")
    op.execute("DROP TYPE IF EXISTS event_type         CASCADE")
    op.execute("DROP TYPE IF EXISTS sod_status         CASCADE")
    op.execute("DROP TYPE IF EXISTS sod_severity       CASCADE")
    op.execute("DROP TYPE IF EXISTS risk_tier          CASCADE")
    op.execute("DROP TYPE IF EXISTS identity_status    CASCADE")
    op.execute("DROP TYPE IF EXISTS identity_class     CASCADE")
